### ISSUE TITLE
bug: bk-swiper bug

### ISSUE THREAD

**Issue by caohua** [TencentBlueKing/bkui-vue2#146]
<bk-swiper class="swiper" :pics="pics" :is-loop="pics.length > 1" :loop-time="5000"></bk-swiper>
如果 pics 或 list 属性的初始值为空数组，会报错。因为源码 <section class="bk-swiper-home"> 的 v-if="sourceList.length" 影响 this.initStatus() 中获取不到 ele.offsetWidth // undefined。

**Comment by zhanxu33** [comment]
新版已修复
