### ISSUE TITLE
add: 新增组件 - City 城市选择器

### ISSUE THREAD

**Issue by caohua** [TencentBlueKing/bkui-vue2#16]
【问题描述】 
【add】快速选择中国城市，常用于地图等基于位置的城市选择场景

**Comment by huangkaoya** [comment]
我觉得这个蓝鲸可以专门弄个业务组件集合。

**Comment by ielgnaw** [comment]
issue 先关闭，这个做成业务组件。

业务组件的源码管理之后与 @caohua 讨论
