### ISSUE TITLE
bug: Cascade级联选择器使用bug

### ISSUE THREAD

**Issue by caohua** [TencentBlueKing/bkui-vue2#19]
【问题描述】 
【bug】级联选择器，在 :filter="true" 条件下，对级联选择器赋予初值之后，下拉选项会自动展开，且初值无法展示，但点击级联选择器的输入框后初值会重新展示出来

**Comment by zhoulujun** [comment]
我们查一下

**Comment by zhoulujun** [comment]
目前 Cascade级联选择器并无 filter属性
http://open.oa.com/static_api/v3/components_vue/2.0/example/index.html#/cascade
![wecom-temp-a2b1494236ea61528992d56d2130eaa8](https://user-images.githubusercontent.com/4243366/132443850-8fd4a7a6-e4cc-48f6-a2b2-b5b91a3a092f.png)

**Comment by ielgnaw** [comment]
是不是 trigger 设置成 hover 了，如果 trigger 设置成 hover 的话，会有异常，不过这是 hover 的本质意思，所以这种场景下，不要设置为 hover。
