### ISSUE TITLE
【feature】有没有支持类似element-ui这种数据表格的计划

### ISSUE THREAD

**Issue by ghost680** [TencentBlueKing/bkui-vue2#210]
![image](https://user-images.githubusercontent.com/58067499/149081394-af6e1d00-057e-4963-aae6-fa4395914884.png)

**Comment by ielgnaw** [comment]
参见 [折叠功能](https://magicbox.bk.tencent.com/static_api/v3/components_vue/2.0/example/index.html#/table?anchor=zhe-die-gong-neng)

在这里，展开时，可以根据自己的业务场景设置 loading 来实现懒加载的效果
