### ISSUE TITLE
bug: 组件tab一开始下划线没有，点击后才出现

### ISSUE THREAD

**Issue by caohua** [TencentBlueKing/bkui-vue2#23]
【问题描述】 
【bug】Dialog嵌套Tab，tab一开始下划线没有，点击后才出现

![image](https://user-images.githubusercontent.com/5043740/130404573-7ebeef87-c5d7-4638-9d06-236535c8328a.png)

**Comment by caohua** [comment]
tab和dialog结合使用的问题原因是dialog生成机制导致的，dialog是默认生成dom，但处于隐藏状态，导致tab就会提前计算滑块的位置，但由于是隐藏状态，计算不准确

**Comment by ielgnaw** [comment]
初始化的时候，如果父元素 display none 了，此时可通过 dom 本身的 border-right 来做

https://github.com/TencentBlueKing/bkui-vue2/pull/47/files#diff-6afb0c9e3a3310ccb664e48c69f46b6bde6f0571650076c68d6e61c71a10f7bc
