### ISSUE TITLE
[Bug]: select 远程搜索结果无法显示

### ISSUE THREAD

**Issue by zhanxu33** [TencentBlueKing/bkui-vue2#255]
复现步骤：
1. select 搜索采用远程搜索，接口返回数据，和初始化列表不一致
2. 选择初始化列表没有的数据
3. 无法显示选中的数据

原因：
1. 关闭弹框的时候，触发 watch focus
2. 触发 resetSearchValue，设置搜索字符串为空
3. 触发 watch searchValue，调用接口获取初始化列表
4. 触发 watch options，调用 setSelectedOptions，`this.selectedOptions = this.optionsMap[this.selected]`，导致显示为空

**Comment by HubuHito** [comment]
不要使用index作为key
