### ISSUE TITLE
[upload]组件图片回填不是动态的

### ISSUE THREAD

**Issue by ielgnaw** [TencentBlueKing/bkui-vue2#29]
![image](https://user-images.githubusercontent.com/1153430/131810500-83bb0a08-4756-4309-9ed9-773414f539fa.png)

![image](https://user-images.githubusercontent.com/1153430/131810516-3f09851a-127c-4d79-ab87-56210d465b0d.png)

缺少对files的监听，在实际使用中，回填的内容都是异步获取的，这个回填无法实现

**Comment by forrany** [comment]
已修复并提单
