### ISSUE TITLE
【FEATURE REQUEST】bk-select 组件期望增加选项禁用时的原因描述的配置，如果文字过多可以支持tooltips方式展示

### ISSUE THREAD

**Issue by king2035** [TencentBlueKing/bkui-vue2#294]
`bk-select` 组件期望增加选项禁用时的原因描述的配置，如果文字过多可以支持 `tooltips` 方式展示

期待如下图展示：
![image](https://user-images.githubusercontent.com/58067499/180405862-465b5d04-c377-4a9f-9aeb-337bc813617e.png)

**Comment by ielgnaw** [comment]
这个可以在 option slot 里自己实现
