### ISSUE TITLE
级联组件交互问题

### ISSUE THREAD

**Issue by ielgnaw** [TencentBlueKing/bkui-vue2#31]
![image](https://user-images.githubusercontent.com/1153430/131810823-2662a51a-832f-4bf7-86bd-2f6b185eed29.png)

**Comment by zhoulujun** [comment]
我们查一下

**Comment by ielgnaw** [comment]
trigger 为 hover 的本质意思是就是在 hover 的时候触发，所以这种场景符合预期。正常情况下，这种场景不应该把 trigger 设置为 hover
