### ISSUE TITLE
[number-input]点击箭头value为Number,直接输入为String

### ISSUE THREAD

**Issue by ielgnaw** [TencentBlueKing/bkui-vue2#32]
![image](https://user-images.githubusercontent.com/1153430/131811026-361debb2-9399-4445-a9a1-2c76e2902bfd.png)

当为number-input的时候，应该一直为Number

**Comment by forrany** [comment]
![image](https://user-images.githubusercontent.com/29779326/131942164-b4371507-c07f-4054-bc97-8f3e74d88305.png)


此功能与预期是矛盾的，经讨论，小数点后面保留位数是string才能实现，因此，如果需要强制为number，需业务中自己实现转换
