### ISSUE TITLE
tagInput支持粘贴功能

### ISSUE THREAD

**Issue by 2199202809** [TencentBlueKing/bkui-vue2#355]
tagInput组件

目前状况：
当前在使用tagInput组件时，在输入框使用粘贴时，粘贴的数据并不会显示在输入框内

期望：
希望可以像使用input组件一样，在输入时支持粘贴功能，且不希望粘贴完成后自动生成标签

**Comment by ielgnaw** [comment]
新增 `free-paste` 配置。配置此属性后，可随意粘贴内容至 tag-input，粘贴后**输入回车**，粘贴的内容会自动生成标签

**Comment by ielgnaw** [comment]
bk-magic-vue@2.5.3
