### ISSUE TITLE
bk-table fixed 属性页面宽度变化不能及时响应重新绘制

### ISSUE THREAD

**Issue by zarte** [TencentBlueKing/bkui-vue2#387]
导致 横向滚动条消失与出现临界点时，fixed 高度异常从而遮挡单元格内容。

**Comment by ielgnaw** [comment]
能否给个具体的示例或截图？

**Comment by ielgnaw** [comment]
已修复

https://magicbox.bk.tencent.com/static_api/v3/components_vue/2.0/example/index.html#/changelog?anchor=2.5.6
bk-magic-vue@2.5.6
