### ISSUE TITLE
bug: 【bk-button】outline与loading同时为true时, loading指示器不可见

### ISSUE THREAD

**Issue by lockiechen** [TencentBlueKing/bkui-vue2#404]
1、outline与loading同时为true时l, loading指示器不可见
<img width="120" alt="image" src="https://github.com/TencentBlueKing/bkui-vue2/assets/33082528/0e8bfdd2-f920-45f0-b21e-c2505aca7b8d">
2、设置了hoverTheme，再设置Loading为true, 按钮文字被挤下一行
<img width="119" alt="image" src="https://github.com/TencentBlueKing/bkui-vue2/assets/33082528/16d7c772-4691-4864-8bb9-ba9e81e3d012">

**Comment by ielgnaw** [comment]
已修复

https://magicbox.bk.tencent.com/static_api/v3/components_vue/2.0/example/index.html#/changelog?anchor=2.5.6
bk-magic-vue@2.5.6
