### ISSUE TITLE
table 组件在设置 settings 之后，首次加载后会出现 settings 按钮和拉动label线有一段缝隙偏移 4px

### ISSUE THREAD

**Issue by JJLau626** [TencentBlueKing/bkui-vue2#437]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**PaaS/PaaSAgent版本(The versions used):**
"bk-magic-vue": "2.4.15-beta.13"

**发生了什么(What happened):**
如题

**期望是什么(What you expected to happen):**
去掉缝隙

**如何复现(How to reproduce it):**
添加相应的 setting 即可

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**
![企业微信截图_16934637965009](https://github.com/TencentBlueKing/bkui-vue2/assets/26458821/6c6a33a6-ecdf-4a34-b852-0d2df528049f)

**备注(Anything else we need to know):**
1.截图需要局部放大看才能看出差异。
2.当调整一次settings按钮的label宽度，就又可以变回正常。

**Comment by ielgnaw** [comment]
bk-magic-vue@2.5.8
