### ISSUE TITLE
select 组件的 trigger 插槽有明显的样式问题

### ISSUE THREAD

**Issue by JJLau626** [TencentBlueKing/bkui-vue2#439]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG

**PaaS/PaaSAgent版本(The versions used):**
2.5.8-beta.7

**发生了什么(What happened):**
如题
![image](https://github.com/TencentBlueKing/bkui-vue2/assets/26458821/ab40dc2c-0802-459e-bcdf-594f09ec4ff7)
使用 button 组件自定义 select 的 trigger，就会出现不必要的边框

**期望是什么(What you expected to happen):**
去掉边框，且整个标签元素的 display 方式应该和之前的 button 组件一样是行内元素

**如何复现(How to reproduce it):**
```
              <Select onSelected={this.addDBType}>
                  <Button
                    text
                    slot='trigger'
                  >
                    <div style={{ display: 'flex', alignItems: 'center' }}>
                      <Icon type='plus-circle' />
                      <span>{this.$t('指定DB')}</span>
                    </div>
                  </Button>

                  {this.DBTypeOptionList.map(item => {
                    return (
                      <Option
                        disabled={this.selectedDBType.includes(item.db_system)}
                        id={item.db_system}
                        key={item.db_system}
                        name={item.db_system}
                      ></Option>
                    );
                  })}
                </Select>
```

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by ielgnaw** [comment]
这里可以通过覆盖 `.bk-select` 这个类的样式来实现这样的效果

可以在组件中来判断是否存在 trigger slot 来设置不同的样式，但是这样会担心影响到已有的项目
