### ISSUE TITLE
Table支持colspan & rowspan

### ISSUE THREAD

**Issue by yangyy** [TencentBlueKing/bkui-vue2#457]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):需求提交

**PaaS/PaaSAgent版本(The versions used):**

**发生了什么(What happened):**

**期望是什么(What you expected to happen):**

<img width="1413" alt="image" src="https://github.com/TencentBlueKing/bkui-vue2/assets/1669521/7bd2f165-0481-4fa6-ad00-31588143b671">

**如何复现(How to reproduce it):**

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by ielgnaw** [comment]
https://magicbox.bk.tencent.com/static_api/v3/components_vue/2.0/example/index.html#/table?anchor=he-bing-xing-huo-lie
