### ISSUE TITLE
Tooltips 工具提示（指令）配置项， content:  '*' 时页面渲染错误

### ISSUE THREAD

**Issue by leafage-collb** [TencentBlueKing/bkui-vue2#460]
v-bk-tooltips="{  content: '*' }"

页面渲染错误

<img width="566" alt="tooltips-error" src="https://github.com/TencentBlueKing/bkui-vue2/assets/57822243/712be691-6c66-4f1e-b447-e726392320d9">

**Comment by ielgnaw** [comment]
需要设置 `allowHTML` 为 `false`
