### ISSUE TITLE
table-column使用fixed=“left”或“right”并且行内元素超过3行时，元素的行高度与fixed固定后的行高度不统一。

### ISSUE THREAD

**Issue by ta0tao** [TencentBlueKing/bkui-vue2#476]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**PaaS/PaaSAgent版本(The versions used):**
v2.5.8

**发生了什么(What happened):**
table组件内table-column使用fixed=“left”或“right”并且行内元素超过**3行**时，元素的行高度与fixed固定后的行高度不统一，数据越往下拉，表格行和固定行border错位越大

**期望是什么(What you expected to happen):**
普通行于固定行高度统一

**如何复现(How to reproduce it):**
在浏览器缩放非25%倍率时，dom高度或宽度px会有小数点，例如110%浏览器缩放下。

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**
![image](https://github.com/TencentBlueKing/bkui-vue2/assets/68816290/ec1c5d27-36d5-44fd-95e9-1df0e14ceffb)
![image](https://github.com/TencentBlueKing/bkui-vue2/assets/68816290/be38b8c6-d153-4af1-b743-c4b4fb21b237)
![image](https://github.com/TencentBlueKing/bkui-vue2/assets/68816290/d4d99383-ffc5-4fb1-8966-f39f87151afd)

**备注(Anything else we need to know):**

**Comment by ielgnaw** [comment]
缩小放大均未复现

<img width="523" alt="image" src="https://github.com/TencentBlueKing/bkui-vue2/assets/1153430/c22abcdb-c6c5-4271-b64c-a028bbe5beae">

<img width="987" alt="image" src="https://github.com/TencentBlueKing/bkui-vue2/assets/1153430/ca52d19e-3c77-4730-965e-29fc14629de9">

是不是版本不对，你试试 bk-magic-vue@2.5.9-beta.4 这个版本

**Comment by ta0tao** [comment]
> 缩小放大均未复现
> 
> <img alt="image" width="523" src="https://private-user-images.githubusercontent.com/1153430/298004971-c22abcdb-c6c5-4271-b64c-a028bbe5beae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTQ1NDIsIm5iZiI6MTcwNTY1NDI0MiwicGF0aCI6Ii8xMTUzNDMwLzI5ODAwNDk3MS1jMjJhYmNkYi1jNmM1LTQyNzEtYjY0Yy1hMDI4YmJlNWJlYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTlUMDg1MDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTliMzUyMjk0YzVmMTU4OTA2YWJhNmE4NzliYTE1NGFmNzk2OTFhMGZiODJkODZmMDJkZGYwMThmNmJkOTZhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.a7bQdRxxaM9tkVh2if3gpgna_Xq-YW_acWh3yXMzR_E"> <img alt="image" width="987" src="https://private-user-images.githubusercontent.com/1153430/298005175-ca52d19e-3c77-4730-965e-29fc14629de9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTQ1NDIsIm5iZiI6MTcwNTY1NDI0MiwicGF0aCI6Ii8xMTUzNDMwLzI5ODAwNTE3NS1jYTUyZDE5ZS0zYzc3LTQ3MzAtOTY1ZS0yOWZjMTQ2MjlkZTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTlUMDg1MDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmY1ODZkMDM2ODU3NjIyZWVlZmJiOGY0ZDcwYzVlYWJkOWM2MjA3M2MwM2FhNDg4YzNkNGFjN2NjOTFkOWM2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.je8u_wgjlOhL0YR27NoQnZCwphoatiVDC5afBibJ0GE">
> 是不是版本不对，你试试 bk-magic-vue@2.5.9-beta.4 这个版本

数据量要够大，可以创建100条数据，浏览器缩放调到110%。在75%，125%的情况下宽高是没小数的。
