### ISSUE TITLE
Select/下拉组件 - 分组下拉，希望分组可展开、收起

### ISSUE THREAD

**Issue by ielgnaw** [TencentBlueKing/bkui-vue2#56]
![image](https://user-images.githubusercontent.com/1153430/132731571-10131953-09b0-491e-bf59-c72cd8c7ca54.png)

场景： 以RT作为分组，选择组里的字段

类似功能组件： 级联选择器：被产品否决，认为在一级列表只有1、2个的时候，不好用

**Comment by xintaoLi** [comment]
![image](https://user-images.githubusercontent.com/9812285/133256621-9e819223-a78c-4263-a1be-935f9be32cf8.png)
目前组件已经支持此功能
