### ISSUE TITLE
<bk-form-item>表单项 label描述信息desc属性使用html，当页面触发update时，desc没有渲染出来

### ISSUE THREAD

**Issue by xu-code** [TencentBlueKing/bkui-vue2#563]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**PaaS/PaaSAgent版本(The versions used):**
PaaS

**发生了什么(What happened):**

表单的fbk-form-item，desc属性使用html，当页面触发update时，desc没有渲染出来
![表单desc使用html文本失效](https://github.com/TencentBlueKing/bkui-vue2/assets/55622423/df340537-5fa7-44b7-ad4c-b3b7abbf9869)
desc内容：
![image](https://github.com/TencentBlueKing/bkui-vue2/assets/55622423/b27271e1-3ca6-406a-8da8-865c772a0595)

**期望是什么(What you expected to happen):**
修改表单不影响表单项 label描述信息的展示

**如何复现(How to reproduce it):**
如上面的gif图片
desc: 
`{
    html: '<h1>你好</h1>'
}`
`<bk-form-item label="项目名称" :required="true" :property="'name'" :desc="customDesc">
                <bk-input v-model="formData.name"></bk-input>
            </bk-form-item>`
修改表单项的值，再hover到label信息，描述未展开

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by ielgnaw** [comment]
无复现

bk-magic-vue@2.5.9-beta.37

https://github.com/user-attachments/assets/f902ad1a-f8f1-4cc0-b75e-8cdf248fc82f
