### ISSUE TITLE
input标签可以限制表情输入

### ISSUE THREAD

**Issue by lhzzforever** [TencentBlueKing/bkui-vue2#565]
需求：想通过直接在input标签提供一个props就可以限制表情包符号输入
/**
 *  限制表情包
 *
 * @param {str} str 传入的字符
 *
 */
export function isEmojiCharacter (str) {
  const emojiReg = /(\ud83c[\udf00-\udfff])|(\ud83d[\udc00-\ude4f\ude80-\udeff])|[\u2600-\u2B55]/g;
  if (str.match(emojiReg)) {
    return true;
  }
  for (let i = 0; i < str.length; i++) {
    const hs = str.charCodeAt(i);
    if (hs >= 0xd800 && hs <= 0xdbff) {
      if (str.length > 1) {
        const ls = str.charCodeAt(i + 1);
        const uc = ((hs - 0xd800) * 0x400) + (ls - 0xdc00) + 0x10000;
        if (uc >= 0x1d000 && uc <= 0x1f77f) {
          return true;
        }
      }
    } else if (str.length > 1) {
      const ls = str.charCodeAt(i + 1);
      if (ls === 0x20e3) {
        return true;
      }
    } else {
      if (hs >= 0x2100 && hs <= 0x27ff) {
        return true;
      } else if (hs >= 0x2B05 && hs <= 0x2b07) {
        return true;
      } else if (hs >= 0x2934 && hs <= 0x2935) {
        return true;
      } else if (hs >= 0x3297 && hs <= 0x3299) {
        return true;
      } else if (
        hs === 0xa9 || hs === 0xae || hs === 0x303d || hs === 0x3030
        || hs === 0x2b55 || hs === 0x2b1c || hs === 0x2b1b
        || hs === 0x2b50) {
        return true;
      }
    }
  }
}

**Comment by ielgnaw** [comment]
组件里加个配置，改好了把版本告诉你

**Comment by ielgnaw** [comment]
bk-magic-vue@2.5.9-beta.37

`allow-emoji` 属性，默认为 true
