### ISSUE TITLE
feature（input）：避免在中文拼音输入时显示中间状态

### ISSUE THREAD

**Issue by useryuyu** [TencentBlueKing/bkui-vue2#580]
在处理中文输入时，会遇到一个问题，即在拼音输入过程中，输入法会显示拼音的中间状态。这种状态会通过 v-model 立即反映在数据绑定上，从而在你的界面上显示出拼音的中间状态，希望处理下这个问题。

**Comment by ielgnaw** [comment]
bk-magic-vue@2.5.9-beta.41

**Comment by ielgnaw** [comment]
bk-magic-vue@2.5.9-beta.42
