### ISSUE TITLE
bug(select): select 组件在开启支持自定义输入配置项 `allow-create` 的同时设置了 placeholder 属性会出现 placeholder 遮住自定义输入的情况

### ISSUE THREAD

**Issue by JayCC1** [TencentBlueKing/bkui-vue2#585]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
`BUG反馈`

**版本(The versions used):**
`2.5.9-beta.38`

**发生了什么(What happened):**
在placeholder存在的时候手动输入然后不失焦的话那么placeholder就会一直存在然后遮住输入的内容

**期望是什么(What you expected to happen):**
自定义手动输入了内容后，placeholder应该需要消失

**如何复现(How to reproduce it):**
👇👇👇

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**
https://github.com/user-attachments/assets/58430be5-a83d-4e1f-8dd0-850b9b8fdce5

**备注(Anything else we need to know):**

**Comment by HubuHito** [comment]
@JayCC1 设置了placeholder应该不生效才对，这个allow-create有点小问题，应该是下面这样的

![image](https://github.com/user-attachments/assets/6429ca87-7bf2-479f-a8f5-83a96130eeaf)

**Comment by HubuHito** [comment]
@JayCC1 自动聚焦搜索框和placeholder问题关注 https://github.com/TencentBlueKing/bkui-vue2/pull/587 PR，残影问题需要提供具体案例再定位看看

**Comment by JayCC1** [comment]
> @JayCC1设置了placeholder应该不生效才对，这个allow-create有点小问题，应该是下面这样的
> 
> ![图像](https://private-user-images.githubusercontent.com/17620291/377401815-6429ca87-7bf2-479f-a8f5-83a96130eeaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNTkwNDEsIm5iZiI6MTcyOTE1ODc0MSwicGF0aCI6Ii8xNzYyMDI5MS8zNzc0MDE4MTUtNjQyOWNhODctN2JmMi00NzlmLWE4ZjUtODNhOTYxMzBlZWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA5NTIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4M2M2MmRjMDU1ZWRkNDEzMzcxNjFjYzA5OGJlYzkzZDYwMTEzZDU2NTQ4MDZjNGU0ZjdkODYzODY1YTk5ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5D4Ycv038yJYcvVHa-YG0A71kYMO4mvxgUMW8g8gqlw)

@HubuHito  em...，我理解一下下哈，意思就是说我如果开启了 `allow-create` 配置之后，那么 `placeholder` 的功能就用不了了对吗
