### ISSUE TITLE
SearchSelect 查询选择器 添加可以重新修改交互

### ISSUE THREAD

**Issue by ielgnaw** [TencentBlueKing/bkui-vue2#59]
![image](https://user-images.githubusercontent.com/1153430/132791405-13e3fb3c-69d4-4557-8782-2f8962ec81ee.png)

**Comment by liangling0628** [comment]
因为原有设计组件时并未设计为可编辑的情况 在现有的组件加入可编辑标签改动很大，后续会重新开发一个新的search-select 来做到功能补充
